{-# LANGUAGE DuplicateRecordFields #-}

module Network.HTTP.Request
  ( Header,
    Headers,
    FromResponseBody (..),
    ToRequestBody (..),
    ToForm (..),
    Form (..),
    Manager,
    Method (..),
    Request (..),
    Response (..),
    ResponseBodyException (..),
    StreamBody (..),
    SseEvent (..),
    basicAuth,
    bearerAuth,
    get,
    delete,
    patch,
    post,
    put,
    newManager,
    send,
    sendWith,
    requestMethod,
    requestUrl,
    requestHeaders,
    requestBody,
    responseStatus,
    responseHeaders,
    responseBody,
  )
where

import Network.HTTP.Request.Internal.Auth (basicAuth, bearerAuth)
import Network.HTTP.Request.Internal.Body
  ( Form (..),
    FromResponseBody (..),
    ResponseBodyException (..),
    ToForm (..),
    ToRequestBody (..),
  )
import Network.HTTP.Request.Internal.Client
  ( Manager,
    delete,
    get,
    newManager,
    patch,
    post,
    put,
    send,
    sendWith,
  )
import Network.HTTP.Request.Internal.Types
  ( Header,
    Headers,
    Method (..),
    Request (..),
    Response (..),
    SseEvent (..),
    StreamBody (..),
    requestBody,
    requestHeaders,
    requestMethod,
    requestUrl,
    responseBody,
    responseHeaders,
    responseStatus,
  )
